Introduce #[IsNotEnabled] attribute to complement #[IsEnabled]
Unleash/unleash-client-symfony pull request #33
Opened 2023-08-17 07:00 UTC by Okhoshi

# Description

The `#[IsEnabled]` attribute is really helpful but can't help with negated flags, such as kill switches. The `#[IsNotEnabled]` attribute introduced in this PR aims to fill the need, by just reversing the throwing logic, but keep reusing the infrastructure already in place.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

- [ ] Unit tests
- [ ] Spec Tests
- [x] Integration tests / Manual Tests

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

NB: I couldn't find the tests in this repo, did I miss something ?

2023-08-17 09:44 UTC, RikudouSage requested changes
Thanks! Overall looks good, though I requested some changes, most of them are for consistency.

2023-08-17 09:44 UTC, RikudouSage commented on README.md
> +- `503` - `ServiceUnavailableHttpException` only with `#[IsNotEnabled]`
They should behave the same, meaning 404 should be the default for both.

2023-08-17 09:44 UTC, RikudouSage commented on README.md
> +code `InvalidValueException` will be thrown.
They should behave the same, meaning 404 should be the default for both.

2023-08-17 09:44 UTC, RikudouSage commented on src/Attribute/ControllerAttribute.php
> +    public function shouldThrowException(bool $isFeatureEnabled): bool;
The attribute shouldn't contain any logic, it's a simple value holder.

2023-08-17 09:44 UTC, RikudouSage commented on src/Attribute/IsEnabled.php
> +    }
The attribute shouldn't contain any logic, it's a simple value holder.

2023-08-17 09:44 UTC, RikudouSage commented on src/Attribute/IsNotEnabled.php
> +    }
The attribute shouldn't contain any logic, it's a simple value holder.

2023-08-17 09:44 UTC, RikudouSage commented on src/Listener/ControllerAttributeResolver.php
> +            if ($attribute->shouldThrowException($this->unleash->isEnabled($attribute->getFeatureName()))) {
The attribute shouldn't contain any logic, it's a simple value holder.

2023-08-17 09:44 UTC, RikudouSage commented on src/Attribute/ControllerAttribute.php
> +    public function getErrorCode(): int;
This should have the `#[ExpectedValues]` attribute.

2023-08-17 09:44 UTC, RikudouSage commented on src/Attribute/IsNotEnabled.php
> +    }
This should have the `#[ExpectedValues]` attribute.

2023-08-17 19:28 UTC, RikudouSage reviewed
Looks nice! I'll do a re-review tomorrow when I'm less tired but so far I can't find anything wrong with it.

2023-08-18 12:32 UTC, mathroc approved these changes

2023-08-18 17:20 UTC, RikudouSage commented on src/Listener/ControllerAttributeResolver.php
> +            if ($throwException) {
It's not really meant to be implemented, it's a fairly internal part of how the bundle works and isn't meant to be implemented in userland.

2023-08-20 20:11 UTC, Okhoshi commented on README.md
> +- `503` - `ServiceUnavailableHttpException` only with `#[IsNotEnabled]`
Also, given that the only input given to the function is the `$isFeatureEnabled` boolean, there's not so much any custom attribute would be able to do besides what `IsEnabled`/`IsNotEnabled` are already providing 😸

2023-08-20 21:08 UTC, RikudouSage approved these changes
Looks good! I'll be releasing this tomorrow.

2023-08-20 21:09 UTC, merged