draft: feat: Unleash as env variable processor
Unleash/unleash-client-symfony pull request #60
Opened 2024-03-01 17:10 UTC by ybenhssaien

# Description

Please include a summary of the change and which issue is fixed (if any).

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

- [ ] Unit tests
- [ ] Spec Tests
- [ ] Integration tests / Manual Tests

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-03-07 16:21 UTC, RikudouSage requested changes

2024-03-07 16:21 UTC, RikudouSage commented on src/DependencyInjection/UnleashEnvVarProcessor.php
> +    }
Please use constructor promotion to be consistent with the rest of the code:

```suggestion
    public function __construct(private Unleash $client)
    {
    }
```

2024-03-07 16:21 UTC, RikudouSage commented on src/DependencyInjection/UnleashEnvVarProcessor.php
> +    public function getEnv(string $prefix, string $name, \Closure $getEnv): bool
Please import the `\Closure` to be consistent with the rest of the codebase.

2024-03-07 16:21 UTC, RikudouSage commented on src/Resources/config/services.yaml
> +      $client: '@unleash.client.unleash'
Please add the tag here:

```suggestion
  unleash.client.env_var_processor:
    class: Unleash\Client\Bundle\DependencyInjection\UnleashEnvVarProcessor
    arguments:
      $client: '@unleash.client.unleash'
    tags:
      - container.env_var_processor
```

2024-03-07 16:21 UTC, RikudouSage commented on src/UnleashClientBundle.php
> +            ->addTag('container.env_var_processor');
Please remove this changes, the tag should be added in the yaml configuration.

2024-03-13 19:21 UTC, RikudouSage commented on src/DependencyInjection/UnleashEnvVarProcessor.php
> +        return $value || filter_var($getEnv($name), FILTER_VALIDATE_BOOL);
Looking at this here, I don't think this is the correct approach... There should be some differentiation between Unleash returning false and the feature not existing. What happens here is that when the feature is evaluated to false a default is used, which IMO is not correct.

What do you think @sighphyre?

2024-03-14 14:56 UTC, sighphyre commented on src/DependencyInjection/UnleashEnvVarProcessor.php
> +        return $value || filter_var($getEnv($name), FILTER_VALIDATE_BOOL);
@RikudouSage Absolutely agree, PHP SDK does support default value as part of the isEnabled call, which is probably a better place for it. That should mean the fallback is only used when the toggle is missing, which is generally the correct flow for an SDK

Side note, if this isn't already using a context provider, I'd consider passing a context as well. Some toggle configurations, like a gradual rollout with a custom stickiness will always resolve (or should, I haven't checked) to false without a context, which is usually not what one wants

2024-03-14 15:01 UTC, RikudouSage commented on src/DependencyInjection/UnleashEnvVarProcessor.php
> +        return $value || filter_var($getEnv($name), FILTER_VALIDATE_BOOL);
@sighphyre This uses an instance provided by the Symfony dependency injection, meaning it already has the correct context.

@ybenhssaien Can you use the default value in the call to `isEnabled()`? It should be something like this:

```suggestion
        return $this->client->isEnabled($name, default: filter_var($getEnv($name), FILTER_VALIDATE_BOOL));
```

2024-04-25 11:30 UTC, closed without merging